[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mimi = "e4e893b0-ee5e-52ea-8111-44b3bdec128c"
MimiGIVE = "08b927d4-7a58-4cf8-85d0-bad32a16dfbc"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
